/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.PerguntaController;
import dao.FeedbackDAO;
import dao.PerguntaDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author guilh
 */
public class TelaAdicionarPerguntaCoordenador extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdicionarPerguntaCoordenador
     */
    public TelaAdicionarPerguntaCoordenador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enunciadoButton = new javax.swing.JButton();
        enunciadoTextField = new javax.swing.JTextField();
        alternativa1Button = new javax.swing.JButton();
        alternativa1TextField = new javax.swing.JTextField();
        alternativa2Button = new javax.swing.JButton();
        alternativa2TextField = new javax.swing.JTextField();
        alternativa3Button = new javax.swing.JButton();
        alternativa3TextField = new javax.swing.JTextField();
        alternativa4Button = new javax.swing.JButton();
        alternativa4TextField = new javax.swing.JTextField();
        alternativaCorretaButton = new javax.swing.JButton();
        alternativaCorretaTextField = new javax.swing.JTextField();
        salvarButton = new javax.swing.JButton();
        sairButton = new javax.swing.JButton();
        dificuldadeButton = new javax.swing.JButton();
        dificuldadeTextField = new javax.swing.JTextField();
        feedbackButton = new javax.swing.JButton();
        feedbackTextField = new javax.swing.JTextField();
        telaAdicionarPerguntaCoordenadorLable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enunciadoButton.setText("Clique aqui para adicionar o enunciado");
        enunciadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enunciadoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(enunciadoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 260, 90));

        enunciadoTextField.setBackground(new java.awt.Color(8, 54, 114));
        enunciadoTextField.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        enunciadoTextField.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(enunciadoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 1220, 90));

        alternativa1Button.setText("Clique aqui para adicionar a alternativa 1");
        alternativa1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativa1ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(alternativa1Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 260, 100));

        alternativa1TextField.setBackground(new java.awt.Color(8, 54, 114));
        alternativa1TextField.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        alternativa1TextField.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(alternativa1TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 1370, 100));

        alternativa2Button.setText("Clique aqui para adicionar a alternativa 2");
        alternativa2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativa2ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(alternativa2Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 260, 100));

        alternativa2TextField.setBackground(new java.awt.Color(8, 54, 114));
        alternativa2TextField.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        alternativa2TextField.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(alternativa2TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 1370, 100));

        alternativa3Button.setText("Clique aqui para adicionar a alternativa 3");
        alternativa3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativa3ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(alternativa3Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 260, 110));

        alternativa3TextField.setBackground(new java.awt.Color(8, 54, 114));
        alternativa3TextField.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        alternativa3TextField.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(alternativa3TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 1370, 110));

        alternativa4Button.setText("Clique aqui para adicionar a alternativa 4");
        alternativa4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativa4ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(alternativa4Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 630, 260, 100));

        alternativa4TextField.setBackground(new java.awt.Color(8, 54, 114));
        alternativa4TextField.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        alternativa4TextField.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(alternativa4TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 630, 1370, 100));

        alternativaCorretaButton.setText("Insira a alternativa CORRETA:");
        alternativaCorretaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativaCorretaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(alternativaCorretaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 760, 260, 100));

        alternativaCorretaTextField.setBackground(new java.awt.Color(8, 54, 114));
        alternativaCorretaTextField.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        alternativaCorretaTextField.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(alternativaCorretaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 760, 1370, 100));

        salvarButton.setContentAreaFilled(false);
        salvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(salvarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 423, 340, 120));

        sairButton.setContentAreaFilled(false);
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sairButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 570, 340, 120));

        dificuldadeButton.setText("Indique a dificuldade da questão (Fácil, Médio, Difícil ou Milhão)");
        dificuldadeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dificuldadeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(dificuldadeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 900, 380, 100));

        dificuldadeTextField.setBackground(new java.awt.Color(8, 54, 114));
        dificuldadeTextField.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        dificuldadeTextField.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(dificuldadeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 900, 660, 100));

        feedbackButton.setText("Clique aqui para indicar o feedback:");
        feedbackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(feedbackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 900, 310, 100));

        feedbackTextField.setBackground(new java.awt.Color(8, 54, 114));
        feedbackTextField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        feedbackTextField.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(feedbackTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 900, 700, 100));

        telaAdicionarPerguntaCoordenadorLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/GerenciarPerguntasAdicionar3.png"))); // NOI18N
        getContentPane().add(telaAdicionarPerguntaCoordenadorLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enunciadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enunciadoButtonActionPerformed
        enunciadoTextField.setVisible(true);
        enunciadoButton.setVisible(false);
        enunciadoTextField.requestFocus();
    }//GEN-LAST:event_enunciadoButtonActionPerformed

    private void alternativa1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativa1ButtonActionPerformed
        alternativa1TextField.setVisible(true);
        alternativa1Button.setVisible(false);
        alternativa1TextField.requestFocus();
    }//GEN-LAST:event_alternativa1ButtonActionPerformed

    private void alternativa2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativa2ButtonActionPerformed
        alternativa2TextField.setVisible(true);
        alternativa2Button.setVisible(false);
        alternativa2TextField.requestFocus();
    }//GEN-LAST:event_alternativa2ButtonActionPerformed

    private void alternativa3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativa3ButtonActionPerformed
        alternativa3TextField.setVisible(true);
        alternativa3Button.setVisible(false);
        alternativa3TextField.requestFocus();
    }//GEN-LAST:event_alternativa3ButtonActionPerformed

    private void alternativa4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativa4ButtonActionPerformed
        alternativa4TextField.setVisible(true);
        alternativa4Button.setVisible(false);
        alternativa4TextField.requestFocus();
    }//GEN-LAST:event_alternativa4ButtonActionPerformed

    private void alternativaCorretaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativaCorretaButtonActionPerformed
        alternativaCorretaTextField.setVisible(true);
        alternativaCorretaButton.setVisible(false);
        alternativaCorretaTextField.requestFocus();
    }//GEN-LAST:event_alternativaCorretaButtonActionPerformed

    private void salvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarButtonActionPerformed

        try {
            String enunciado = enunciadoTextField.getText();

            String[] alternativas = {
                alternativa1TextField.getText(),
                alternativa2TextField.getText(),
                alternativa3TextField.getText(),
                alternativa4TextField.getText(),
                alternativaCorretaTextField.getText(),
            };

            String feedback = feedbackTextField.getText();

            int dificuldade = converterDificuldade(dificuldadeTextField.getText());

            var p = new PerguntaDAO();
            var f = new FeedbackDAO();
            var controller = new PerguntaController(p, f);
            controller.cadastrarPerguntaComFeedback(enunciado, 1, dificuldade, feedback);
            controller.cadastrarAlternativas(enunciado, alternativas);
            JOptionPane.showMessageDialog(null, "Pergunta adicionada com sucesso!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex);
            ex.printStackTrace();
            return; // Se der erro, não continua o processo
        }
    }//GEN-LAST:event_salvarButtonActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        var telaMenuPerguntaCoordenador = new TelaMenuGerenciarPerguntasCoordenador();
        telaMenuPerguntaCoordenador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sairButtonActionPerformed

    private void dificuldadeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dificuldadeButtonActionPerformed
        dificuldadeTextField.setVisible(true);
        dificuldadeButton.setVisible(false);
        dificuldadeTextField.requestFocus();
    }//GEN-LAST:event_dificuldadeButtonActionPerformed

    private void feedbackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackButtonActionPerformed
        feedbackTextField.setVisible(true);
        feedbackButton.setVisible(false);
        feedbackTextField.requestFocus();
    }//GEN-LAST:event_feedbackButtonActionPerformed

public int converterDificuldade(String dificuldade) {
        switch (dificuldade.toLowerCase()) {
            case "fácil":
                return 1;
            case "médio":
                return 2;
            case "difícil":
                return 3;
            case "milhão":
                return 4;
            default:
                return 5; // vai pro limbo do banco de dados kkkkkkkkkkkk
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarPerguntaCoordenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarPerguntaCoordenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarPerguntaCoordenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarPerguntaCoordenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdicionarPerguntaCoordenador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alternativa1Button;
    private javax.swing.JTextField alternativa1TextField;
    private javax.swing.JButton alternativa2Button;
    private javax.swing.JTextField alternativa2TextField;
    private javax.swing.JButton alternativa3Button;
    private javax.swing.JTextField alternativa3TextField;
    private javax.swing.JButton alternativa4Button;
    private javax.swing.JTextField alternativa4TextField;
    private javax.swing.JButton alternativaCorretaButton;
    private javax.swing.JTextField alternativaCorretaTextField;
    private javax.swing.JButton dificuldadeButton;
    private javax.swing.JTextField dificuldadeTextField;
    private javax.swing.JButton enunciadoButton;
    private javax.swing.JTextField enunciadoTextField;
    private javax.swing.JButton feedbackButton;
    private javax.swing.JTextField feedbackTextField;
    private javax.swing.JButton sairButton;
    private javax.swing.JButton salvarButton;
    private javax.swing.JLabel telaAdicionarPerguntaCoordenadorLable;
    // End of variables declaration//GEN-END:variables
}
