/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author guilh
 */
public class TelaMenuGerenciarPerguntasCoordenador extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenuGerenciarPerguntasCoordenador
     */
    public TelaMenuGerenciarPerguntasCoordenador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voltarButton = new javax.swing.JButton();
        editarPerguntaButton = new javax.swing.JButton();
        adicionarButton = new javax.swing.JButton();
        telaMenuPerguntasCoordenadorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        voltarButton.setBackground(new java.awt.Color(8, 54, 114));
        voltarButton.setFont(new java.awt.Font("Segoe UI Variable", 1, 36)); // NOI18N
        voltarButton.setForeground(new java.awt.Color(255, 255, 255));
        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(voltarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 680, 350, 110));

        editarPerguntaButton.setContentAreaFilled(false);
        editarPerguntaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarPerguntaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editarPerguntaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 380, 120));

        adicionarButton.setContentAreaFilled(false);
        adicionarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(adicionarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 480, 420, 120));

        telaMenuPerguntasCoordenadorLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MenuGerenciarPerguntas_1.png"))); // NOI18N
        getContentPane().add(telaMenuPerguntasCoordenadorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editarPerguntaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarPerguntaButtonActionPerformed
        var telaGerenciarParguntasEditar = new TelaGerenciarPerguntasEditar();
        telaGerenciarParguntasEditar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_editarPerguntaButtonActionPerformed

    private void adicionarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarButtonActionPerformed
        var telaAdicionarPerguntaCoordenador = new TelaAdicionarPerguntaCoordenador();
        telaAdicionarPerguntaCoordenador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_adicionarButtonActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        var telaMenuCoordenador = new TelaMenuDoCoordenador();
        telaMenuCoordenador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenuGerenciarPerguntasCoordenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenuGerenciarPerguntasCoordenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenuGerenciarPerguntasCoordenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenuGerenciarPerguntasCoordenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenuGerenciarPerguntasCoordenador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarButton;
    private javax.swing.JButton editarPerguntaButton;
    private javax.swing.JLabel telaMenuPerguntasCoordenadorLabel;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
